
# Q4. Run Apriori algorithm to find frequent itemsets and association rules

In [9]:
pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.19.0-py2.py3-none-any.whl (1.3 MB)
Requirement already satisfied: pandas>=0.24.2 in c:\users\prave\anaconda3\lib\site-packages (from mlxtend) (1.3.4)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\prave\anaconda3\lib\site-packages (from mlxtend) (3.4.3)
Requirement already satisfied: setuptools in c:\users\prave\anaconda3\lib\site-packages (from mlxtend) (58.0.4)
Requirement already satisfied: scikit-learn>=0.20.3 in c:\users\prave\anaconda3\lib\site-packages (from mlxtend) (0.24.2)
Requirement already satisfied: numpy>=1.16.2 in c:\users\prave\anaconda3\lib\site-packages (from mlxtend) (1.20.3)
Requirement already satisfied: joblib>=0.13.2 in c:\users\prave\anaconda3\lib\site-packages (from mlxtend) (1.1.0)
Requirement already satisfied: scipy>=1.2.1 in c:\users\prave\anaconda3\lib\site-packages (from mlxtend) (1.7.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\prave\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\prave\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (8.4.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\prave\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: cycler>=0.10 in c:\users\prave\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.10.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\prave\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.4)
Requirement already satisfied: six in c:\users\prave\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib>=3.0.0->mlxtend) (1.16.0)
Requirement already satisfied: pytz>=2017.3 in c:\users\prave\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2021.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\prave\anaconda3\lib\site-packages (from scikit-learn>=0.20.3->mlxtend) (2.2.0)
Installing collected packages: mlxtend
Successfully installed mlxtend-0.19.0
Note: you may need to restart the kernel to use updated packages.

In [30]:
import pandas as pd
import numpy as np
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori

In [31]:
trans=pd.read_csv('data_prac4.csv')
trans

    c1   c2   c3   c4
0    a    b    c  NaN
1  NaN    b    c  NaN
2    a  NaN  NaN    d
3  NaN    b    c    d
4    a  NaN    c    d
5    a  NaN    c  NaN
6    a    b    c    d
7  NaN    b    c  NaN
8    a    b  NaN  NaN
9  NaN  NaN  NaN    d

In [32]:
ts = pd.get_dummies(trans.unstack().dropna()).groupby(level=1).sum()
ts

   a  b  c  d
0  1  1  1  0
1  0  1  1  0
2  1  0  0  1
3  0  1  1  1
4  1  0  1  1
5  1  0  1  0
6  1  1  1  1
7  0  1  1  0
8  1  1  0  0
9  0  0  0  1

### 1.1	Use minimum support as 50% and minimum confidence as 75%

In [33]:
frequent_itemsets = apriori(ts, min_support=0.5, use_colnames=True)
frequent_itemsets

   support itemsets
0      0.6      (a)
1      0.6      (b)
2      0.7      (c)
3      0.5      (d)
4      0.5   (b, c)

In [34]:
from mlxtend.frequent_patterns import association_rules
association_rules(frequent_itemsets, metric="confidence", min_threshold=0.75)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(b),(c),0.6,0.7,0.5,0.833333,1.190476,0.08,1.8

### 1.2	Use minimum support as 60% and minimum confidence as 60 %

In [35]:
frequent_itemsets = apriori(ts, min_support=0.6, use_colnames=True)
frequent_itemsets

   support itemsets
0      0.6      (a)
1      0.6      (b)
2      0.7      (c)

In [36]:
from mlxtend.frequent_patterns import association_rules
association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6)

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction]
Index: []